CREATE EXTENSION IF NOT EXISTS CITEXT;
CREATE UNLOGGED TABLE IF NOT EXISTS Users (
    id SERIAL PRIMARY KEY,
    nickname CITEXT UNIQUE,
    fullname CITEXT,
    about TEXT,
    email CITEXT UNIQUE
);